// Code generated by "stringer -type=StatusEnum"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Excluded - -1]
	_ = x[NoDisease-0]
	_ = x[Disease-1]
	_ = x[Died-2]
	_ = x[LostToFollowUp-3]
}

const _StatusEnum_name = "ExcludedNoDiseaseDiseaseDiedLostToFollowUp"

var _StatusEnum_index = [...]uint8{0, 8, 17, 24, 28, 42}

func (i StatusEnum) String() string {
	i -= -1
	if i < 0 || i >= StatusEnum(len(_StatusEnum_index)-1) {
		return "StatusEnum(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _StatusEnum_name[_StatusEnum_index[i]:_StatusEnum_index[i+1]]
}
